# Generated by Django 4.0.1 on 2022-01-24 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture_cloud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
