# Generated by Django 4.0.1 on 2022-01-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture_cloud', '0003_country_food_delete_choice_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=50)),
            ],
        ),
    ]
