# Generated by Django 4.0.1 on 2022-01-31 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture_cloud', '0004_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='country_flag',
            field=models.ImageField(default='', upload_to='culture_cloud/countryFlags/'),
            preserve_default=False,
        ),
    ]
