# Generated by Django 4.0.1 on 2022-02-02 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('culture_cloud', '0005_country_country_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='countryBannerVid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=80)),
                ('video_description', models.CharField(max_length=500)),
                ('video_upload', models.FileField(upload_to='culture_cloud/countryBannerImg/')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culture_cloud.country')),
            ],
        ),
        migrations.CreateModel(
            name='countryBannerImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=80)),
                ('image_description', models.CharField(max_length=500)),
                ('image_upload', models.ImageField(upload_to='culture_cloud/countryBannerImg/')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culture_cloud.country')),
            ],
        ),
    ]
