# Generated by Django 4.0.1 on 2022-02-02 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('culture_cloud', '0006_countrybannervid_countrybannerimg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food',
        ),
    ]
